/**
 * Resolves the salon-admin base URL for links generated by functions whose
 * CALLER is a different app than the one being linked to (e.g. backoffice
 * approving a waitlist lead or sending a promo email — both link into
 * salon-admin, not back into backoffice itself). Reflecting the caller's own
 * Origin back (as getBaseUrlFromRequest does) would be wrong here since
 * caller and target are different apps/domains.
 *
 * When the caller is a local dev server (localhost/127.0.0.1 — regardless of
 * which port, since backoffice and salon-admin run on different ports even
 * in dev), target salon-admin's own local dev port instead of the
 * configured SALON_APP_URL, so links generated from a local backoffice
 * against the dev Supabase project are actually clickable in dev.
 */
export function getSalonAppUrl(req: Request): string {
  const callerOrigin = req.headers.get("origin") || req.headers.get("referer");
  const isLocalCaller = (() => {
    try {
      const host = callerOrigin ? new URL(callerOrigin).hostname : "";
      return host === "localhost" || host === "127.0.0.1";
    } catch {
      return false;
    }
  })();

  if (isLocalCaller) return "http://localhost:8080";

  return (
    Deno.env.get("SALON_APP_URL") ||
    Deno.env.get("BASE_URL") ||
    "https://app.salonmagik.com"
  );
}
