// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type AppStorageKey =
  | "sb-salonmagik-salon"
  | "sb-salonmagik-booking"
  | "sb-salonmagik-client"
  | "sb-salonmagik-backoffice";

export function createSupabaseClient(storageKey: AppStorageKey) {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      storageKey,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

// Default export for salon-admin until per-app clients are wired
export const supabase = createSupabaseClient("sb-salonmagik-salon");
