// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type AppStorageKey =
  | "sb-salonmagik-salon"
  | "sb-salonmagik-booking"
  | "sb-salonmagik-client"
  | "sb-salonmagik-backoffice";

type SupabaseClientMap = Partial<
  Record<string, ReturnType<typeof createClient<Database>>>
>;

const CLIENT_CACHE_KEY = "__salonmagik_supabase_clients__";

function getClientCache(): SupabaseClientMap {
  const globalObj = globalThis as typeof globalThis & {
    [CLIENT_CACHE_KEY]?: SupabaseClientMap;
  };
  if (!globalObj[CLIENT_CACHE_KEY]) {
    globalObj[CLIENT_CACHE_KEY] = {};
  }
  return globalObj[CLIENT_CACHE_KEY]!;
}

export function createSupabaseClient(storageKey: AppStorageKey) {
  const projectRefFromUrl = (() => {
    try {
      return new URL(SUPABASE_URL).hostname.split(".")[0];
    } catch {
      return "";
    }
  })();
  const projectRef = import.meta.env.VITE_SUPABASE_PROJECT_ID || projectRefFromUrl;
  const scopedStorageKey = projectRef ? `${storageKey}-${projectRef}` : storageKey;

  const cache = getClientCache();
  if (cache[scopedStorageKey]) {
    return cache[scopedStorageKey]!;
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      storageKey: scopedStorageKey,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  cache[scopedStorageKey] = client;
  return client;
}

// Default export for salon-admin until per-app clients are wired
export const supabase = createSupabaseClient("sb-salonmagik-salon");
