// The scenario matrix (design section 14) as data — the single source both
// docs/test-plans/payments-e2e.cells.json (generated by generate-manifest.ts)
// and the scenario suites read from, so the applicability table in the test
// plan and the cells actually executed can never drift apart.

export type Currency = "GHS" | "NGN";
export const CURRENCIES: Currency[] = ["GHS", "NGN"];

export type Intent = "BOOK" | "CPT" | "SPT" | "INV" | "MSG" | "SUB";
export type Scenario = "OK" | "FAIL" | "ABD-C" | "ABD-N" | "DUP" | "REF";

export const INTENTS: Intent[] = ["BOOK", "CPT", "SPT", "INV", "MSG", "SUB"];
export const SCENARIOS: Scenario[] = ["OK", "FAIL", "ABD-C", "ABD-N", "DUP", "REF"];

export interface ApplicabilityCell {
  intent: Intent;
  scenario: Scenario;
  applicable: boolean;
  reason?: string;
}

// Design section 14.2.
const NOT_APPLICABLE_REASONS: Partial<Record<Intent, Partial<Record<Scenario, string>>>> = {
  CPT: {
    "ABD-N": "ABD-N is BOOK-only — for every other intent, an abandoned no-charge session leaves only an orphaned payment_intents row, which BOOK-ABD-N already covers as a shared-path property.",
  },
  SPT: {
    "ABD-N": "ABD-N is BOOK-only (see CPT).",
    FAIL: "The failure branch in processWebhook is intent-independent and is covered by BOOK-FAIL/SUB-FAIL — n/a-covered-elsewhere, not n/a-untested.",
    REF: "No product refund path reaches a salon-purse-topup transaction (refund is reached from the salon-admin refund dialog against a customer-facing transaction, or via cancelled-appointment) — the absence is itself recorded as a finding, not a passing cell.",
  },
  INV: {
    "ABD-N": "ABD-N is BOOK-only (see CPT).",
    FAIL: "The failure branch in processWebhook is intent-independent and is covered by BOOK-FAIL/SUB-FAIL — n/a-covered-elsewhere, not n/a-untested.",
  },
  MSG: {
    "ABD-C": "Messaging credit purchase has no abandoned-but-charged product surface distinct from BOOK-ABD-C's coverage of the shared webhook path.",
    "ABD-N": "ABD-N is BOOK-only (see CPT).",
    FAIL: "The failure branch in processWebhook is intent-independent and is covered by BOOK-FAIL/SUB-FAIL — n/a-covered-elsewhere, not n/a-untested.",
    REF: "No product refund path reaches a messaging-credit-purchase transaction — the absence is itself recorded as a finding, not a passing cell.",
  },
  SUB: {
    "ABD-N": "ABD-N is BOOK-only (see CPT).",
    REF: "Subscription activation has no refund product surface in scope for this run.",
  },
};

export function applicabilityMatrix(): ApplicabilityCell[] {
  const rows: ApplicabilityCell[] = [];
  for (const intent of INTENTS) {
    for (const scenario of SCENARIOS) {
      const reason = NOT_APPLICABLE_REASONS[intent]?.[scenario];
      rows.push({ intent, scenario, applicable: reason === undefined, reason });
    }
  }
  return rows;
}

export function isApplicable(intent: Intent, scenario: Scenario): boolean {
  return NOT_APPLICABLE_REASONS[intent]?.[scenario] === undefined;
}

/** Requirement ids per scenario (design section 14.3), independent of intent. */
export const REQUIREMENT_IDS_BY_SCENARIO: Record<Scenario, string[]> = {
  OK: ["FR-6", "FR-7", "FR-8"],
  FAIL: ["FR-9"],
  "ABD-C": ["FR-10"],
  "ABD-N": ["FR-11"],
  DUP: ["FR-12"],
  REF: ["FR-13"],
};

export const TRANSPORT_CELL_IDS = ["OK", "TAMPERED", "WRONG-CURRENCY-SECRET", "MALFORMED"] as const;
export type TransportCellKind = typeof TRANSPORT_CELL_IDS[number];

export const PAYOUT_CELL_IDS = [
  "W-OK",
  "W-FAILED",
  "W-REVERSED",
  "W-DUP-REQ",
  "W-DUP-EVT",
  "W-OVER",
  "W-FLOOR",
  "W-OTP",
] as const;
export type PayoutCellKind = typeof PAYOUT_CELL_IDS[number];

export const PAYOUT_REQUIREMENT_IDS: Record<PayoutCellKind, string[]> = {
  "W-OK": ["FR-16"],
  "W-FAILED": ["FR-17"],
  "W-REVERSED": ["FR-17"],
  "W-DUP-REQ": ["FR-18"],
  "W-DUP-EVT": ["FR-21"],
  "W-OVER": ["FR-19"],
  "W-FLOOR": ["FR-19"],
  "W-OTP": ["FR-20"],
};

export const REFUND_SUB_CELLS = ["REF-a", "REF-b", "REF-c"] as const;
export type RefundSubCell = typeof REFUND_SUB_CELLS[number];
export const REFUND_REQUIREMENT_IDS: Record<RefundSubCell, string[]> = {
  "REF-a": ["FR-13"],
  "REF-b": ["FR-13"],
  "REF-c": ["FR-13"],
};

export function cellId(intent: Intent, scenario: Scenario, currency: Currency): string {
  return `PAY-${intent}-${scenario}-${currency}`;
}
